name: Backend Continous Deployment

on:
  push:
    branches:
    - main
  workflow_dispatch:
env:
  REPO_NAME: "backend"
jobs:
  test:
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: starter/backend
      steps:
        - name: Checkout source code
          uses: actions/checkout@v3
  
        - name: Setup Python
          uses: actions/setup-python@v4
          with:
            python-version: "3.10"
        - name: Install pipenv
          run: pip install pipenv
        - name: Install dependencies
          run: pipenv install
        - name: Run lint
          run: pipenv run test
  build:
    runs-on: ubuntu-latest
    needs: test
    defaults:
      run:
        working-directory: starter/backend
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Configure AWS credential
        uses: aws-actions/configure-aws-credentials@v2
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1
      - name: Login AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build and push the image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ env.REPO_NAME }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
