name: Backend Continous Deployment

on:
  push:
    branches:
    - main
  workflow_dispatch:
jobs:
  test:
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: starter/backend
      steps:
        - name: Checkout source code
          uses: actions/checkout@v3
  
        - name: Setup Python
          uses: actions/setup-python@v4
          with:
            python-version: "3.10"
        - name: Install pipenv
          run: pip install pipenv
        - name: Install dependencies
          run: pipenv install
        - name: Run lint
          run: pipenv run test
  build:
    runs-on: ubuntu-latest
    needs: test
    defaults:
      run:
        working-directory: starter/backend
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
