name: Frontend Continuous Integration

on:
  pull_request:
    types:
      - closed
    branches:
      - main

  workflow_dispatch:
env:
  REPO_NAME: "frontend"
jobs:
  lint:
    runs-on:  ubuntu-latest
    defaults:
      run:
        working-directory: starter/frontend
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup Node JS
        uses: actions/setup-node@v3
        with:
          node-version: '21'
      - name: Install dependencies
        run: npm ci
      - name: Run lint
        run: npm run lint
  test:
    runs-on:  ubuntu-latest
    defaults:
      run:
        working-directory: starter/frontend
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup Node JS
        uses: actions/setup-node@v3
        with:
          node-version: '21'
      - name: Install dependencies
        run: npm ci
      - name: Run test
        run: npm test
  build:
    runs-on: ubuntu-latest
    needs: [lint,test]
    defaults:
      run:
        working-directory: starter/frontend
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup Node JS
        uses: actions/setup-node@v3
        with:
          node-version: '21'
      - name: Cache Node.js 
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci
      - name: Run test
        run: npm run test
      - name: Run docker build
        run: docker build -t movie-app:latest .
