name: Frontend Continuous Deployment

on:
  push:
    branches:
      - main

  workflow_dispatch:
jobs:
  test:
    runs-on:  ubuntu-latest
    defaults:
      run:
        working-directory: starter/frontend
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup Node JS
        uses: actions/setup-node@v3
        with:
          node-version: '21'
      - name: Install dependencies
        run: npm ci
      - name: Run test
        run: npm test
  build:
    runs-on: ubuntu-latest
    needs: test
    defaults:
      run:
        working-directory: starter/frontend
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Configure AWS credential
        uses: aws-actions/configure-aws-credentials@v2
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1
      - name: Login AWS ECR
        uses: aws-actions/amazon-ecr-login@v1
      
