name: Frontend Continuous Integration

on:
  pull_request:
    types:
      - closed
    branches:
      - main

  workflow_dispatch:
jobs:
  lint:
    runs-on:  ubuntu-latest
    defaults:
      run:
        working-directory: starter/frontend
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup Node JS
        uses: actions/setup-node@v3
        with:
          node-version: '21'
      - name: Install dependencies
        run: npm ci
      - name: Run lint
        run: npm run lint