name: Frontend Continuous Integration

on:
  pull_request:
    types:
      - closed
    branches:
      - main

  workflow_dispatch:

jobs:
  hello:
  runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/frontend
    steps:
      - name: Checkout source code
        run: echo "Checkout source code"